apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ogw6agx2y-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ogw6agx2y-java-quarkus-gitops